name: inspecazure
title: Azure InSpec Profile
maintainer: David Mitchell
copyright: David Mitchell
copyright_email: david.mitchell@gft.com
license: Apache-2.0
summary: An InSpec Compliance Profile For Azure
version: 0.1.0
inspec_version: '>= 2.2.7'
depends:
- name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
- platform: azure
